// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrf8Dt5T9_skPZN1xHTs6Lk8Z2x67u6r4',
    appId: '1:806694052777:web:0ee12a3243d0a3c21f1ab8',
    messagingSenderId: '806694052777',
    projectId: 'fji-example',
    authDomain: 'fji-example.firebaseapp.com',
    storageBucket: 'fji-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZ0OpEioMJR-adK0yINYsrVwxxzEUNyo',
    appId: '1:806694052777:android:c69934cee886a2571f1ab8',
    messagingSenderId: '806694052777',
    projectId: 'fji-example',
    storageBucket: 'fji-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAuuQhnE9UgWxQfVatQSQmKlT1c88yP1k',
    appId: '1:806694052777:ios:8e7fe6681b7f50d71f1ab8',
    messagingSenderId: '806694052777',
    projectId: 'fji-example',
    storageBucket: 'fji-example.appspot.com',
    iosBundleId: 'com.example.fjiExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAuuQhnE9UgWxQfVatQSQmKlT1c88yP1k',
    appId: '1:806694052777:ios:8e7fe6681b7f50d71f1ab8',
    messagingSenderId: '806694052777',
    projectId: 'fji-example',
    storageBucket: 'fji-example.appspot.com',
    iosBundleId: 'com.example.fjiExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrf8Dt5T9_skPZN1xHTs6Lk8Z2x67u6r4',
    appId: '1:806694052777:web:3032af2953a6396b1f1ab8',
    messagingSenderId: '806694052777',
    projectId: 'fji-example',
    authDomain: 'fji-example.firebaseapp.com',
    storageBucket: 'fji-example.appspot.com',
  );
}
