name: fji_example
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  fji_example_core_flutter:
    path: ../fji_example_core_flutter

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_ui_firestore: ^2.0.1
  flutter_chat_ui: ^2.9.1
  flutter_chat_core: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^16.0.0

flutter:
  uses-material-design: true
